name: post-commit check

on:
  push:
    branches: main

jobs:
  universum_check:
    name: Basic Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello World"
