name: pre-commit check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, 'feat/*']

jobs:
  check-code-with-universum:
    name : Check code with universum
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependency
      run: |
        pip install universum
        pip install gitpython
        sudo apt-get install clang-format
        sudo apt-get install git

    - name: Universum
      run:
        python -u -m universum
        --vcs-type="ghactions"
        --ghactions-payload="@${{ github.event_path }}"
        --ghactions-token="${{ secrets.GITHUB_TOKEN }}"
        --report-to-review
        --no-diff
        --fail-unsuccessful

    - name: Collect artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: artifacts
        path: artifacts

    

