name: pre-commit check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, 'feat/*']

jobs:
  check-code-with-cpp-linter-action: 
    name: Check code with cpp-linter-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: 'cppcoreguidelines-*'
          # The following value will only update a single comment
          # in a pull request's thread. Set it to false to disable the comment.
          # Set it to true to post a new comment (and delete the old comment).
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
          exit 1
  
  check-code-with-universum:
    name : Check code with universum
    runs-on: ubuntu-latest
    steps:

    - name: Setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependency
      run: |
        pip install universum
        pip install gitpython
        sudo apt-get install clang-format
        sudo apt-get install git

    - name: Universum
      run:
        python -u -m universum
        --vcs-type="ghactions"
        --ghactions-payload="@${{ github.event_path }}"
        --ghactions-token="${{ secrets.GITHUB_TOKEN }}"
        --report-to-review
        --no-diff
        --fail-unsuccessful

    - name: Collect artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: artifacts
        path: artifacts

    

