name: pre-commit check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, 'feat/*']

jobs:
  universum_check:
    name: Basic Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello World"
